package com.devdyna.gtnihilo.other;

import java.util.List;

public class DataBase {

    public static List<String> veins = List.of(
            "bauxite_vein_end",
            "magnetite_vein_end",
            "naquadah_vein",
            "pitchblende_vein",
            "scheelite_vein",
            "sheldonite_vein",
            "banded_iron_vein",
            "beryllium_vein",
            "certus_quartz_vein",
            "manganese_vein",
            "molybdenum_vein",
            "monazite_vein",
            "nether_quartz_vein",
            "redstone_vein",
            "saltpeter_vein",
            "sulfur_vein",
            "tetrahedrite_vein",
            "topaz_vein",
            "apatite_vein",
            "cassiterite_vein",
            "coal_vein",
            "copper_tin_vein",
            "galena_vein",
            "garnet_tin_vein",
            "garnet_vein",
            "iron_vein",
            "lubricant_vein",
            "magnetite_vein_ow",
            "mineral_sand_vein",
            "nickel_vein",
            "salts_vein",
            "oilsands_vein",
            "copper_vein",
            "diamond_vein",
            "lapis_vein",
            "manganese_vein_ow",
            "mica_vein",
            "olivine_vein",
            "redstone_vein_ow",
            "sapphire_vein");

    public static int[] colors = {
            0xFFFF5733,
            0xFF33FF57,
            0xFF3357FF,
            0xFFF1C40F,
            0xFF8E44AD,
            0xFF1ABC9C,
            0xFF2ECC71,
            0xFF3498DB,
            0xFFE74C3C,
            0xFF9B59B6,
            0xFF34495E,
            0xFF16A085,
            0xFF27AE60,
            0xFF2980B9,
            0xFFC0392B,
            0xFFD35400,
            0xFF7D3C98,
            0xFF2980B9,
            0xFFF39C12,
            0xFFBDC3C7,
            0xFF2C3E50,
            0xFF7F8C8D,
            0xFF95A5A6,
            0xFFECF0F1,
            0xFF1F618D,
            0xFFF8C471,
            0xFFD5F5E3,
            0xFFD98880,
            0xFFAED6F1,
            0xFFA9DFBF,
            0xFFBB8FCE,
            0xFFF5B041,
            0xFFF7DC6F,
            0xFF52BE80,
            0xFF5DADE2,
            0xFF58D68D,
            0xFFA04000,
            0xFFA569BD,
            0xFF7FB3D5,
            0xFFABEBC6
    };

}
